apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: java
          image: zeinab817/app-java:v15
          ports:
            - containerPort: 8090
